# Generated by Django 5.0.6 on 2024-06-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
