# Generated by Django 5.0.6 on 2024-06-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeapp', '0002_employee_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Date',
            new_name='doj',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(null=True, upload_to='Profile.images/'),
        ),
    ]
